### ISSUE TITLE
eval(.) causes problem for Emacs

### ISSUE THREAD

**Issue by ashkan-leo** [oh-my-fish/plugin-virtualfish#3]
The following line causes problem for Emacs `exec-path-from-shell`:
`eval (eval $VIRTUALFISH_PYTHON -m virtualfish $VIRTUALFISH_PLUGINS 2>/dev/null)`

Similar issues is discussed in [this](https://github.com/syl20bnr/spacemacs/issues/4755) Spacemacs thread also.

I tried to write the following line without `eval`, but I don't see any way to execute `$VIRTUALFISH_PYTHON` without using `eval`. 

`eval $VIRTUALFISH_PYTHON -m virtualfish $VIRTUALFISH_PLUGINS 2>/dev/null | source` is the best thing I could do.

Any suggestion besides removing `$VIRTUALFISH_PYTHON` and using python directly in the script?

**Comment by timanin** [comment]
Hi @ashkan-leo, thanks for reporting this issue.

Indeed, this is due to a bug introduced in fish 2.5.0 and they have an issue for this: https://github.com/fish-shell/fish-shell/issues/3809

Good news is that it's working fine in fish 2.6.0. Bad news is that it hasn't been released yet. They aim for releasing on May 3rd according to https://github.com/fish-shell/fish-shell/issues/3806

Your solution is what was also recommended in the bug discussion. I am hesitant to change the plugin as it will be fixed relatively soon in fish, and, personally, I rebuilt from HEAD, using brew on a mac:

``` shell
brew install fish --HEAD
```

For Linux they have nightly releases: https://github.com/fish-shell/fish-shell/wiki/Nightly-builds

Hope this helps?

**Comment by ashkan-leo** [comment]
I upgraded fish and that solved the problem, thanks!
